language: ruby
services:
  - redis
  - rabbitmq
  - postgresql

env:
  - JRUBY_OPTS="--dev -Xcext.enabled=false -Xcompile.invokedynamic=false"

rvm:
  - jruby-1.7.16
  - jruby-head

jdk: openjdk7

sudo: false
cache: bundler

before_script:
  - psql -c "CREATE DATABASE test_results_test;" -U postgres
  - cp config/travis.example.yml config/travis.yml
  - bundle exec rake db:migrate

script: bundle exec rspec spec

matrix:
  allow_failures:
    - rvm: jruby-head
