language: ruby
services:
  - redis
  - rabbitmq
  - postgresql

env:
  - JRUBY_OPTS="--dev -Xcext.enabled=false -Xcompile.invokedynamic=false"

rvm:
  - ruby-2.2.2

sudo: false
cache: bundler

before_script:
  - cp config/travis.example.yml config/travis.yml
  - # psql -c "CREATE DATABASE test_results_test;" -U postgres
  - # bundle exec rake db:migrate

script: bundle exec rspec spec

matrix:
  allow_failures:
    - rvm: jruby-head
