language: ruby

addons:
    postgresql: "9.3"

services:
  - redis
  - rabbitmq
  - postgresql


rvm:
  - ruby-2.2.2

sudo: false
cache: bundler

before_script:
  - cp config/travis.example.yml config/travis.yml
  - psql -c "CREATE DATABASE travis_test_results_test;" -U postgres
  - bundle exec rake db:migrate

script: bundle exec rspec spec
