database_defaults: &database_defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning
  host: localhost
  port: 5432

development:
  test_results:
    gc_pooling_interval: 15
    gc_remove_after: 86400
    threads: 3
    pretty_json: true
    results_path: '/var/lib/final-ci/test-results'
  test_results_database:
    <<: *database_defaults
    database: travis_development

test:
  test_results_database:
    <<: *database_defaults
    database: travis_test
